algoritmo "CalcSomaMédia"
// Função :
// Autor : Hugo Oliveira Soares
// Data : 18/02/2020
// Seção de Declarações 
var n1, n2, n3, soma : inteiro
    media : real

inicio
      escreva("Informe um numero = ")
      leia(n1)
      escreva("Informe outro numero = ")
      leia(n2)
      escreva("Informe mais um numero = ")
      leia(n3)
      soma <- n1 + n2 + n3
      media <- soma / 3
      escreval("Media = ", media)
// Seção de Comandos 
fimalgoritmo
